# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Form1sXFbIv.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QWidget)

class Ui_master(object):
    def setupUi(self, master):
        if not master.objectName():
            master.setObjectName(u"master")
        master.resize(730, 623)
        master.setStyleSheet(u"background-color: rgb(33, 66, 66);")
        master.setDocumentMode(False)
        self.actionchangepassword = QAction(master)
        self.actionchangepassword.setObjectName(u"actionchangepassword")
        self.actioncreatesuperuser = QAction(master)
        self.actioncreatesuperuser.setObjectName(u"actioncreatesuperuser")
        self.actionremove_stale_contenttypes = QAction(master)
        self.actionremove_stale_contenttypes.setObjectName(u"actionremove_stale_contenttypes")
        self.actioncheck = QAction(master)
        self.actioncheck.setObjectName(u"actioncheck")
        self.actioncompilemessages = QAction(master)
        self.actioncompilemessages.setObjectName(u"actioncompilemessages")
        self.actioncreatecachetable = QAction(master)
        self.actioncreatecachetable.setObjectName(u"actioncreatecachetable")
        self.actiondbshell = QAction(master)
        self.actiondbshell.setObjectName(u"actiondbshell")
        self.actiondiffsettings = QAction(master)
        self.actiondiffsettings.setObjectName(u"actiondiffsettings")
        self.actiondumpdata = QAction(master)
        self.actiondumpdata.setObjectName(u"actiondumpdata")
        self.actionflush = QAction(master)
        self.actionflush.setObjectName(u"actionflush")
        self.actioninspectdb = QAction(master)
        self.actioninspectdb.setObjectName(u"actioninspectdb")
        self.actionloaddata = QAction(master)
        self.actionloaddata.setObjectName(u"actionloaddata")
        self.actionmakemessages = QAction(master)
        self.actionmakemessages.setObjectName(u"actionmakemessages")
        self.actionmakemigrations = QAction(master)
        self.actionmakemigrations.setObjectName(u"actionmakemigrations")
        self.actionmigrate = QAction(master)
        self.actionmigrate.setObjectName(u"actionmigrate")
        self.actionoptimizemigration = QAction(master)
        self.actionoptimizemigration.setObjectName(u"actionoptimizemigration")
        self.actionsendtestemail = QAction(master)
        self.actionsendtestemail.setObjectName(u"actionsendtestemail")
        self.actionshell = QAction(master)
        self.actionshell.setObjectName(u"actionshell")
        self.actionshowmigrations = QAction(master)
        self.actionshowmigrations.setObjectName(u"actionshowmigrations")
        self.actionsqlflush = QAction(master)
        self.actionsqlflush.setObjectName(u"actionsqlflush")
        self.actionsqlmigrate = QAction(master)
        self.actionsqlmigrate.setObjectName(u"actionsqlmigrate")
        self.actionsqlsequencereset = QAction(master)
        self.actionsqlsequencereset.setObjectName(u"actionsqlsequencereset")
        self.actionssquashmigrations = QAction(master)
        self.actionssquashmigrations.setObjectName(u"actionssquashmigrations")
        self.actionstartapp = QAction(master)
        self.actionstartapp.setObjectName(u"actionstartapp")
        self.actionstartproject = QAction(master)
        self.actionstartproject.setObjectName(u"actionstartproject")
        self.actiontest = QAction(master)
        self.actiontest.setObjectName(u"actiontest")
        self.actiontestserver = QAction(master)
        self.actiontestserver.setObjectName(u"actiontestserver")
        self.actionclearsessions = QAction(master)
        self.actionclearsessions.setObjectName(u"actionclearsessions")
        self.actioncollectstatic = QAction(master)
        self.actioncollectstatic.setObjectName(u"actioncollectstatic")
        self.actionfindstatic = QAction(master)
        self.actionfindstatic.setObjectName(u"actionfindstatic")
        self.actionrunserver = QAction(master)
        self.actionrunserver.setObjectName(u"actionrunserver")
        self.actionExit = QAction(master)
        self.actionExit.setObjectName(u"actionExit")
        self.centralwidget = QWidget(master)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(5, -4, 720, 556))
        self.label.setPixmap(QPixmap(u"back1.png"))
        self.label.setScaledContents(True)
        self.pushButton_runserver = QPushButton(self.centralwidget)
        self.pushButton_runserver.setObjectName(u"pushButton_runserver")
        self.pushButton_runserver.setGeometry(QRect(113, 153, 171, 41))
        font = QFont()
        font.setPointSize(16)
        self.pushButton_runserver.setFont(font)
        self.pushButton_runserver.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.pushButton_runserver.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(34, 68, 68);\n"
"selection-background-color: rgb(214, 214, 214);")
        self.pushButton_show_databse = QPushButton(self.centralwidget)
        self.pushButton_show_databse.setObjectName(u"pushButton_show_databse")
        self.pushButton_show_databse.setGeometry(QRect(113, 233, 171, 41))
        self.pushButton_show_databse.setFont(font)
        self.pushButton_show_databse.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_admin = QPushButton(self.centralwidget)
        self.pushButton_admin.setObjectName(u"pushButton_admin")
        self.pushButton_admin.setGeometry(QRect(113, 313, 171, 41))
        self.pushButton_admin.setFont(font)
        self.pushButton_admin.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_open_shell = QPushButton(self.centralwidget)
        self.pushButton_open_shell.setObjectName(u"pushButton_open_shell")
        self.pushButton_open_shell.setGeometry(QRect(113, 393, 171, 41))
        self.pushButton_open_shell.setFont(font)
        self.pushButton_open_shell.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_check = QPushButton(self.centralwidget)
        self.pushButton_check.setObjectName(u"pushButton_check")
        self.pushButton_check.setGeometry(QRect(112, 469, 171, 41))
        self.pushButton_check.setFont(font)
        self.pushButton_check.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_flush_databse = QPushButton(self.centralwidget)
        self.pushButton_flush_databse.setObjectName(u"pushButton_flush_databse")
        self.pushButton_flush_databse.setGeometry(QRect(442, 469, 171, 41))
        self.pushButton_flush_databse.setFont(font)
        self.pushButton_flush_databse.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_make_migration = QPushButton(self.centralwidget)
        self.pushButton_make_migration.setObjectName(u"pushButton_make_migration")
        self.pushButton_make_migration.setGeometry(QRect(442, 233, 171, 41))
        self.pushButton_make_migration.setFont(font)
        self.pushButton_make_migration.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_create_new_app = QPushButton(self.centralwidget)
        self.pushButton_create_new_app.setObjectName(u"pushButton_create_new_app")
        self.pushButton_create_new_app.setGeometry(QRect(442, 153, 171, 41))
        self.pushButton_create_new_app.setFont(font)
        self.pushButton_create_new_app.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_apply_migration = QPushButton(self.centralwidget)
        self.pushButton_apply_migration.setObjectName(u"pushButton_apply_migration")
        self.pushButton_apply_migration.setGeometry(QRect(441, 313, 171, 41))
        self.pushButton_apply_migration.setFont(font)
        self.pushButton_apply_migration.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_show_migration = QPushButton(self.centralwidget)
        self.pushButton_show_migration.setObjectName(u"pushButton_show_migration")
        self.pushButton_show_migration.setGeometry(QRect(441, 393, 171, 41))
        self.pushButton_show_migration.setFont(font)
        self.pushButton_show_migration.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_clear = QPushButton(self.centralwidget)
        self.pushButton_clear.setObjectName(u"pushButton_clear")
        self.pushButton_clear.setGeometry(QRect(584, 555, 142, 33))
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(5, 556, 463, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.lineEdit.setFont(font1)
        self.lineEdit.setStyleSheet(u"background-color: rgb(241, 241, 241);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit.setMaxLength(1000)
        self.pushButton_open_site = QPushButton(self.centralwidget)
        self.pushButton_open_site.setObjectName(u"pushButton_open_site")
        self.pushButton_open_site.setGeometry(QRect(469, 555, 115, 33))
        self.pushButton_open_site.setFont(font)
        self.pushButton_open_site.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_command = QLineEdit(self.centralwidget)
        self.lineEdit_command.setObjectName(u"lineEdit_command")
        self.lineEdit_command.setGeometry(QRect(15, 35, 521, 31))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.lineEdit_command.setFont(font2)
        self.lineEdit_command.setStyleSheet(u"background-color: rgb(34, 68, 68);\n"
"color: rgb(0, 255, 247);")
        self.lineEdit_command.setMaxLength(1000)
        self.pushButton_execute = QPushButton(self.centralwidget)
        self.pushButton_execute.setObjectName(u"pushButton_execute")
        self.pushButton_execute.setGeometry(QRect(537, 35, 91, 33))
        self.pushButton_execute.setFont(font)
        self.pushButton_execute.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_help = QPushButton(self.centralwidget)
        self.pushButton_help.setObjectName(u"pushButton_help")
        self.pushButton_help.setGeometry(QRect(628, 35, 91, 33))
        self.pushButton_help.setFont(font)
        self.pushButton_help.setStyleSheet(u"background-color: rgb(152, 222, 218);\n"
"color: rgb(0, 0, 0);")
        master.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(master)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 730, 33))
        self.menubar.setFont(font2)
        self.menubar.setStyleSheet(u"background-color: rgb(34, 68, 68);\n"
"\n"
"selection-background-color: rgb(58, 115, 116);\n"
"color: rgb(0, 255, 247);")
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Auth = QMenu(self.menubar)
        self.menu_Auth.setObjectName(u"menu_Auth")
        self.menu_Contenttypes = QMenu(self.menubar)
        self.menu_Contenttypes.setObjectName(u"menu_Contenttypes")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menusessions = QMenu(self.menubar)
        self.menusessions.setObjectName(u"menusessions")
        self.menustaticfiles = QMenu(self.menubar)
        self.menustaticfiles.setObjectName(u"menustaticfiles")
        master.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Auth.menuAction())
        self.menubar.addAction(self.menu_Contenttypes.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menusessions.menuAction())
        self.menubar.addAction(self.menustaticfiles.menuAction())
        self.menu_File.addAction(self.actionExit)
        self.menu_Auth.addAction(self.actionchangepassword)
        self.menu_Auth.addAction(self.actioncreatesuperuser)
        self.menu_Contenttypes.addAction(self.actionremove_stale_contenttypes)
        self.menuAbout.addAction(self.actioncheck)
        self.menuAbout.addAction(self.actioncompilemessages)
        self.menuAbout.addAction(self.actioncreatecachetable)
        self.menuAbout.addAction(self.actiondbshell)
        self.menuAbout.addAction(self.actiondiffsettings)
        self.menuAbout.addAction(self.actiondumpdata)
        self.menuAbout.addAction(self.actionflush)
        self.menuAbout.addAction(self.actioninspectdb)
        self.menuAbout.addAction(self.actionloaddata)
        self.menuAbout.addAction(self.actionmakemessages)
        self.menuAbout.addAction(self.actionmakemigrations)
        self.menuAbout.addAction(self.actionmigrate)
        self.menuAbout.addAction(self.actionoptimizemigration)
        self.menuAbout.addAction(self.actionsendtestemail)
        self.menuAbout.addAction(self.actionshell)
        self.menuAbout.addAction(self.actionshowmigrations)
        self.menuAbout.addAction(self.actionsqlflush)
        self.menuAbout.addAction(self.actionsqlmigrate)
        self.menuAbout.addAction(self.actionsqlsequencereset)
        self.menuAbout.addAction(self.actionssquashmigrations)
        self.menuAbout.addAction(self.actionstartapp)
        self.menuAbout.addAction(self.actionstartproject)
        self.menuAbout.addAction(self.actiontest)
        self.menuAbout.addAction(self.actiontestserver)
        self.menusessions.addAction(self.actionclearsessions)
        self.menustaticfiles.addAction(self.actioncollectstatic)
        self.menustaticfiles.addAction(self.actionfindstatic)
        self.menustaticfiles.addAction(self.actionrunserver)

        self.retranslateUi(master)

        QMetaObject.connectSlotsByName(master)
    # setupUi

    def retranslateUi(self, master):
        master.setWindowTitle(QCoreApplication.translate("master", u"Django Master v1.0", None))
        self.actionchangepassword.setText(QCoreApplication.translate("master", u"changepassword", None))
        self.actioncreatesuperuser.setText(QCoreApplication.translate("master", u"createsuperuser", None))
        self.actionremove_stale_contenttypes.setText(QCoreApplication.translate("master", u"remove_stale_contenttypes", None))
        self.actioncheck.setText(QCoreApplication.translate("master", u"check", None))
        self.actioncompilemessages.setText(QCoreApplication.translate("master", u"compilemessages", None))
        self.actioncreatecachetable.setText(QCoreApplication.translate("master", u"createcachetable", None))
        self.actiondbshell.setText(QCoreApplication.translate("master", u"dbshell", None))
        self.actiondiffsettings.setText(QCoreApplication.translate("master", u"diffsettings", None))
        self.actiondumpdata.setText(QCoreApplication.translate("master", u"dumpdata", None))
        self.actionflush.setText(QCoreApplication.translate("master", u"flush", None))
        self.actioninspectdb.setText(QCoreApplication.translate("master", u"inspectdb", None))
        self.actionloaddata.setText(QCoreApplication.translate("master", u"loaddata", None))
        self.actionmakemessages.setText(QCoreApplication.translate("master", u"makemessages", None))
        self.actionmakemigrations.setText(QCoreApplication.translate("master", u"makemigrations", None))
        self.actionmigrate.setText(QCoreApplication.translate("master", u"migrate", None))
        self.actionoptimizemigration.setText(QCoreApplication.translate("master", u"optimizemigration", None))
        self.actionsendtestemail.setText(QCoreApplication.translate("master", u"sendtestemail", None))
        self.actionshell.setText(QCoreApplication.translate("master", u"shell", None))
        self.actionshowmigrations.setText(QCoreApplication.translate("master", u"showmigrations", None))
        self.actionsqlflush.setText(QCoreApplication.translate("master", u"sqlflush", None))
        self.actionsqlmigrate.setText(QCoreApplication.translate("master", u"sqlmigrate", None))
        self.actionsqlsequencereset.setText(QCoreApplication.translate("master", u"sqlsequencereset", None))
        self.actionssquashmigrations.setText(QCoreApplication.translate("master", u"squashmigrations", None))
        self.actionstartapp.setText(QCoreApplication.translate("master", u"startapp", None))
        self.actionstartproject.setText(QCoreApplication.translate("master", u"startproject", None))
        self.actiontest.setText(QCoreApplication.translate("master", u"test", None))
        self.actiontestserver.setText(QCoreApplication.translate("master", u"testserver", None))
        self.actionclearsessions.setText(QCoreApplication.translate("master", u"clearsessions", None))
        self.actioncollectstatic.setText(QCoreApplication.translate("master", u"collectstatic", None))
        self.actionfindstatic.setText(QCoreApplication.translate("master", u"findstatic", None))
        self.actionrunserver.setText(QCoreApplication.translate("master", u"runserver", None))
        self.actionExit.setText(QCoreApplication.translate("master", u"Exit", None))
        self.label.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton_runserver.setToolTip(QCoreApplication.translate("master", u"<html><head/><body><p>Python manage.py runserver</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_runserver.setText(QCoreApplication.translate("master", u"Run/Server", None))
        self.pushButton_show_databse.setText(QCoreApplication.translate("master", u"Show Databse", None))
        self.pushButton_admin.setText(QCoreApplication.translate("master", u"Admin", None))
        self.pushButton_open_shell.setText(QCoreApplication.translate("master", u"Open Shell", None))
        self.pushButton_check.setText(QCoreApplication.translate("master", u"Check", None))
        self.pushButton_flush_databse.setText(QCoreApplication.translate("master", u"Flush Database", None))
        self.pushButton_make_migration.setText(QCoreApplication.translate("master", u"Make migration", None))
        self.pushButton_create_new_app.setText(QCoreApplication.translate("master", u"Create New App", None))
        self.pushButton_apply_migration.setText(QCoreApplication.translate("master", u"Apply Migration", None))
        self.pushButton_show_migration.setText(QCoreApplication.translate("master", u"Show Migrations", None))
        self.pushButton_clear.setText(QCoreApplication.translate("master", u"Clear Console", None))
        self.lineEdit.setText(QCoreApplication.translate("master", u"http://127.0.0.1:8000/", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("master", u"Default URL:-http://127.0.0.1:8000/", None))
        self.pushButton_open_site.setText(QCoreApplication.translate("master", u"Open", None))
        self.lineEdit_command.setText(QCoreApplication.translate("master", u"py manage.py runserver", None))
        self.lineEdit_command.setPlaceholderText(QCoreApplication.translate("master", u"(venv)/</Command>/", None))
        self.pushButton_execute.setText(QCoreApplication.translate("master", u"Execute", None))
        self.pushButton_help.setText(QCoreApplication.translate("master", u"Help", None))
        self.menu_File.setTitle(QCoreApplication.translate("master", u"File", None))
        self.menu_Auth.setTitle(QCoreApplication.translate("master", u"Auth", None))
        self.menu_Contenttypes.setTitle(QCoreApplication.translate("master", u"Contenttypes", None))
        self.menuAbout.setTitle(QCoreApplication.translate("master", u"Django", None))
        self.menusessions.setTitle(QCoreApplication.translate("master", u"sessions", None))
        self.menustaticfiles.setTitle(QCoreApplication.translate("master", u"staticfiles", None))
    # retranslateUi

